from __future__ import annotations

from .connector_activities_google_calendar import (
    GOOGLE_CALENDAR_ACTIVITY_DEFINITIONS,
    GOOGLE_CALENDAR_HANDLER_REGISTRY,
)
from .connector_activities_google_drive import (
    GOOGLE_DRIVE_ACTIVITY_DEFINITIONS,
    GOOGLE_DRIVE_HANDLER_REGISTRY,
)
from .connector_activities_google_gmail import (
    GOOGLE_GMAIL_ACTIVITY_DEFINITIONS,
    GOOGLE_GMAIL_HANDLER_REGISTRY,
)
from .connector_activities_google_sheets import (
    GOOGLE_SHEETS_ACTIVITY_DEFINITIONS,
    GOOGLE_SHEETS_HANDLER_REGISTRY,
)

GOOGLE_CONNECTOR_ACTIVITY_DEFINITIONS = (
    *GOOGLE_GMAIL_ACTIVITY_DEFINITIONS,
    *GOOGLE_DRIVE_ACTIVITY_DEFINITIONS,
    *GOOGLE_CALENDAR_ACTIVITY_DEFINITIONS,
    *GOOGLE_SHEETS_ACTIVITY_DEFINITIONS,
)

GOOGLE_HANDLER_REGISTRY = {
    **GOOGLE_GMAIL_HANDLER_REGISTRY,
    **GOOGLE_DRIVE_HANDLER_REGISTRY,
    **GOOGLE_CALENDAR_HANDLER_REGISTRY,
    **GOOGLE_SHEETS_HANDLER_REGISTRY,
}

__all__ = ["GOOGLE_CONNECTOR_ACTIVITY_DEFINITIONS", "GOOGLE_HANDLER_REGISTRY"]
