from __future__ import annotations

from .connector_activities_github_actions import (
    GITHUB_ACTION_ACTIVITY_DEFINITIONS,
    GITHUB_ACTION_HANDLER_REGISTRY,
)
from .connector_activities_github_issues import (
    GITHUB_ISSUE_ACTIVITY_DEFINITIONS,
    GITHUB_ISSUE_HANDLER_REGISTRY,
)
from .connector_activities_github_pulls import (
    GITHUB_PULL_ACTIVITY_DEFINITIONS,
    GITHUB_PULL_HANDLER_REGISTRY,
)
from .connector_activities_github_repos import (
    GITHUB_REPO_ACTIVITY_DEFINITIONS,
    GITHUB_REPO_HANDLER_REGISTRY,
)


GITHUB_CONNECTOR_ACTIVITY_DEFINITIONS = (
    *GITHUB_REPO_ACTIVITY_DEFINITIONS,
    *GITHUB_ISSUE_ACTIVITY_DEFINITIONS,
    *GITHUB_PULL_ACTIVITY_DEFINITIONS,
    *GITHUB_ACTION_ACTIVITY_DEFINITIONS,
)

GITHUB_HANDLER_REGISTRY = {
    **GITHUB_REPO_HANDLER_REGISTRY,
    **GITHUB_ISSUE_HANDLER_REGISTRY,
    **GITHUB_PULL_HANDLER_REGISTRY,
    **GITHUB_ACTION_HANDLER_REGISTRY,
}

__all__ = ["GITHUB_CONNECTOR_ACTIVITY_DEFINITIONS", "GITHUB_HANDLER_REGISTRY"]
