"""Log table schema helpers: identifier validation, data-table naming, and DDL creation."""

from __future__ import annotations

import re
from typing import Any
from uuid import uuid4

from fastapi import HTTPException, status

from backend.database import fetch_one
from backend.schemas import LogDbColumnDefinition, LogDbColumnResponse

_SAFE_ID_RE = re.compile(r"^[a-z][a-z0-9_]{0,62}$")
_PG_TYPE_MAP: dict[str, str] = {
    "text": "TEXT",
    "integer": "INTEGER",
    "real": "DOUBLE PRECISION",
    "boolean": "BOOLEAN",
    "timestamp": "TIMESTAMPTZ",
}


def assert_safe_identifier(name: str) -> str:
    """Raise HTTP 422 if *name* is not a safe SQL identifier; return name."""
    if not _SAFE_ID_RE.match(name):
        raise HTTPException(
            status_code=status.HTTP_422_UNPROCESSABLE_CONTENT,
            detail=(
                f"Invalid identifier '{name}': must start with a lowercase letter "
                "and contain only lowercase letters, digits, and underscores."
            ),
        )
    return name


def data_table_name(table_name: str) -> str:
    """Return the physical data table name for a managed log table."""
    return f"log_data_{table_name}"


def build_create_table_sql(data_table: str, columns: list[LogDbColumnDefinition]) -> str:
    """Build the CREATE TABLE statement for a managed log-data table."""
    col_defs: list[str] = [
        "seq_id BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE",
        "row_id TEXT PRIMARY KEY",
        "automation_id TEXT NOT NULL",
        "inserted_at TIMESTAMPTZ NOT NULL",
    ]
    for col in columns:
        assert_safe_identifier(col.column_name)
        pg_type = _PG_TYPE_MAP.get(col.data_type, "TEXT")
        null_clause = "" if col.nullable else " NOT NULL"
        default_clause = ""
        if col.default_value is not None:
            safe_default = col.default_value.replace("'", "''")
            default_clause = f" DEFAULT '{safe_default}'"
        col_defs.append(f"{col.column_name} {pg_type}{null_clause}{default_clause}")
    return f"CREATE TABLE IF NOT EXISTS {data_table} ({', '.join(col_defs)})"


def create_log_table_ddl(connection: Any, data_table: str, columns: list[LogDbColumnDefinition]) -> None:
    """Execute the CREATE TABLE DDL for a new managed log-data table."""
    sql = build_create_table_sql(data_table, columns)
    connection.execute(sql)


def persist_log_table_metadata(
    connection: Any,
    *,
    table_id: str,
    name: str,
    description: str | None,
    columns: list[LogDbColumnDefinition],
    now: str,
) -> list[LogDbColumnResponse]:
    """Insert log_db_tables and log_db_columns metadata rows; return column responses."""
    connection.execute(
        "INSERT INTO log_db_tables (id, name, description, created_at, updated_at) VALUES (?, ?, ?, ?, ?)",
        (table_id, name, description, now, now),
    )
    col_responses: list[LogDbColumnResponse] = []
    for position, col in enumerate(columns):
        col_id = f"logcol_{uuid4().hex[:10]}"
        connection.execute(
            """
            INSERT INTO log_db_columns
                (id, table_id, column_name, data_type, nullable, default_value, position, created_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                col_id,
                table_id,
                col.column_name,
                col.data_type,
                int(col.nullable),
                col.default_value,
                position,
                now,
            ),
        )
        col_responses.append(
            LogDbColumnResponse(
                id=col_id,
                table_id=table_id,
                column_name=col.column_name,
                data_type=col.data_type,
                nullable=col.nullable,
                default_value=col.default_value,
                position=position,
                created_at=now,
            )
        )
    return col_responses


def get_log_table_row_or_404(connection: Any, table_id: str) -> dict[str, Any]:
    """Fetch the log_db_tables row for *table_id* or raise HTTP 404."""
    row = fetch_one(connection, "SELECT * FROM log_db_tables WHERE id = ?", (table_id,))
    if row is None:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Log table not found.")
    return dict(row)
