from __future__ import annotations

from .builders import action_case, list_case
from .core import RouteSmokeCase, assert_json_response
from .external_mocks import invoke_worker_image_magic_mock, invoke_worker_smtp_send_mock
from .resources import configure_image_magic_tool, configure_smtp_tool, create_inbound_event, create_worker_job
from .resolvers import worker_complete_payload, worker_rpc_headers

RUNTIME_WORKERS_CASES: tuple[RouteSmokeCase, ...] = (
    list_case("healthcheck", "GET", "/health", response_assert=assert_json_response),
    list_case("runtime-status", "GET", "/api/v1/runtime/status", response_assert=assert_json_response),
    list_case("scheduler-jobs", "GET", "/api/v1/scheduler/jobs", response_assert=assert_json_response),
    list_case("dashboard-summary", "GET", "/api/v1/dashboard/summary", response_assert=assert_json_response),
    list_case("dashboard-devices", "GET", "/api/v1/dashboard/devices", response_assert=assert_json_response),
    list_case("dashboard-queue", "GET", "/api/v1/dashboard/queue", response_assert=assert_json_response),
    list_case("dashboard-logs", "GET", "/api/v1/dashboard/logs", response_assert=assert_json_response),
    list_case("dashboard-resource-history", "GET", "/api/v1/dashboard/resource-history", response_assert=assert_json_response),
    list_case("dashboard-resource-dashboard", "GET", "/api/v1/dashboard/resource-dashboard", response_assert=assert_json_response),
    list_case("resource-profile", "GET", "/api/v1/debug/resource-profile", response_assert=assert_json_response),
    list_case(
        "resource-profile-component",
        "GET",
        "/api/v1/debug/resource-profile/automation_executor",
        route_path="/api/v1/debug/resource-profile/{component}",
        response_assert=assert_json_response,
    ),
    action_case(
        "resource-profile-reset",
        "POST",
        "/api/v1/debug/resource-profile/reset",
        204,
    ),
    action_case("dashboard-queue-pause", "POST", "/api/v1/dashboard/queue/pause", 200, response_assert=assert_json_response),
    action_case("dashboard-queue-unpause", "POST", "/api/v1/dashboard/queue/unpause", 200, response_assert=assert_json_response),
    list_case("runtime-triggers", "GET", "/api/v1/runtime/triggers", setup=create_inbound_event, response_assert=assert_json_response),
    list_case("workers-list", "GET", "/api/v1/workers", response_assert=assert_json_response),
    action_case(
        "workers-register",
        "POST",
        "/api/v1/workers/register",
        200,
        payload={
            "worker_id": "worker_smoke_01",
            "name": "Smoke Worker",
            "hostname": "smoke-worker.local",
            "address": "127.0.0.1",
            "capabilities": ["runtime-trigger-execution"],
        },
        response_assert=assert_json_response,
    ),
    action_case(
        "workers-claim-trigger",
        "POST",
        "/api/v1/workers/claim-trigger",
        200,
        setup=create_worker_job,
        payload={"worker_id": "worker_smoke_01"},
        response_assert=assert_json_response,
    ),
    action_case(
        "workers-complete-trigger",
        "POST",
        "/api/v1/workers/complete-trigger",
        200,
        setup=create_worker_job,
        payload=worker_complete_payload,
        response_assert=assert_json_response,
    ),
    action_case(
        "workers-smtp-sync",
        "POST",
        "/api/v1/internal/workers/tools/smtp/sync",
        200,
        headers=worker_rpc_headers,
        payload={
            "enabled": True,
            "bind_host": "127.0.0.1",
            "port": 2525,
            "recipient_email": "recipient@example.com",
        },
        response_assert=assert_json_response,
    ),
    list_case(
        "workers-smtp-status",
        "GET",
        "/api/v1/internal/workers/tools/smtp/status",
        setup=configure_smtp_tool,
        headers=worker_rpc_headers,
        response_assert=assert_json_response,
    ),
    action_case(
        "workers-smtp-send-test",
        "POST",
        "/api/v1/internal/workers/tools/smtp/send-test",
        200,
        setup=configure_smtp_tool,
        headers=worker_rpc_headers,
        payload={
            "mail_from": "smoke@example.com",
            "recipients": ["recipient@example.com"],
            "subject": "Smoke test",
            "body": "Smoke message",
        },
        response_assert=assert_json_response,
        invoke=invoke_worker_smtp_send_mock,
    ),
    action_case(
        "workers-image-magic-execute",
        "POST",
        "/api/v1/internal/workers/tools/image-magic/execute",
        200,
        setup=configure_image_magic_tool,
        headers=worker_rpc_headers,
        payload={
            "input_file": "input.png",
            "output_format": "jpg",
        },
        response_assert=assert_json_response,
        invoke=invoke_worker_image_magic_mock,
    ),
)
